cc_binary(
    name = "wallpaper_mediapipe_runner",
    srcs = ["main.cpp"],
    deps = [
        "//mediapipe/tasks/cc/vision/face_landmarker:face_landmarker",
        "//mediapipe/tasks/cc/vision/utils:image_utils",
        "//third_party:opencv",
        "@com_google_absl//absl/status:statusor",
    ],
)
